
version: '3.8'
services:
  web:
    image: test-springboot-jpa:latest
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=sanbay
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./test_mysql.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data:
   